/**
 * The public API of @rockaway/react, as a report (cairn 0153). What a user may
 * rely on: every name an entry point exports, the class on each component's
 * root and on each part its metadata names, and the attributes its variants
 * and states are selected by. `API.md` is a file snapshot: a change to it is a
 * change to the public API, and a removal or a rename is breaking (0172).
 *
 * Everything else is internal: a class no metadata names, the DOM between the
 * parts, a component-local custom property.
 */
import { readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, test } from 'vitest';
import { block, entriesOf, exportsOf } from '../../../scripts/api-surface.ts';
import { extracted } from '../src/metadata/extracted.ts';
import { type ComponentMeta, components } from '../src/metadata/index.ts';

const root = path.join(import.meta.dirname, '..');

/** Each entry point's files, with `./*` expanded to the component entries it stands for. */
function entries(): { subpath: string; file: string }[] {
  return entriesOf(root).flatMap(({ subpath, files }) =>
    files.flatMap((file) => {
      if (!file.includes('*')) return [{ subpath, file }];
      const dir = path.dirname(file);
      return readdirSync(path.join(root, dir))
        .filter((name) => name.endsWith('.ts'))
        .sort()
        .map((name) => ({
          subpath: subpath.replace('*', name.replace(/\.ts$/, '')),
          file: path.join(dir, name),
        }));
    }),
  );
}

/** The class each component writes on a root it lets a caller add to: `cx('rk-button', className)`. */
function rootClasses(): Map<string, string[]> {
  const dir = path.join(root, 'src/components');
  const out = new Map<string, string[]>();
  for (const name of readdirSync(dir)
    .filter((f) => f.endsWith('.tsx'))
    .sort()) {
    const source = readFileSync(path.join(dir, name), 'utf8');
    const classes = [...source.matchAll(/cx\('(rk-[a-z-]+)'/g)].map((m) => m[1] as string);
    out.set(name, [...new Set(classes)].sort());
  }
  return out;
}

/** A component's public classes: the roots of the files its parts live in, then its named parts. */
function classesOf(meta: ComponentMeta, roots: ReadonlyMap<string, string[]>): string[] {
  const files = meta.anatomy.flatMap((part) =>
    part.kind === 'import' ? [extracted[part.name]?.file ?? ''] : [],
  );
  const own = files.flatMap((file) => roots.get(file) ?? []);
  const parts = meta.anatomy.flatMap((part) => (part.kind === 'element' ? [part.className] : []));
  return [...new Set([...own, ...parts])];
}

function report(): string {
  const sections: string[] = [
    '# @rockaway/react: public API',
    '',
    'Generated by `test/public-api.test.ts` (cairn 0153). A change here is a change to what users rely on: say so in the changeset, and begin it `Breaking:` when something is removed or renamed (0172).',
  ];

  sections.push('', '## Entry points');
  for (const { subpath, file } of entries()) {
    const names =
      file.endsWith('.ts') || file.endsWith('.tsx') ? exportsOf(path.join(root, file)) : [];
    sections.push('', `### \`@rockaway/react${subpath === '.' ? '' : subpath.slice(1)}\``);
    sections.push('', names.length === 0 ? '(a file, not a module)' : block(names));
  }

  sections.push(
    '',
    '## Classes',
    '',
    'On each component root, and on each part its metadata names.',
  );
  const roots = rootClasses();
  for (const meta of components) {
    sections.push(
      '',
      `- ${meta.name}: ${classesOf(meta, roots)
        .map((c) => `\`.${c}\``)
        .join(', ')}`,
    );
  }

  sections.push('', '## Attributes', '', 'Variants, and the states each component draws.');
  for (const meta of components) {
    const variants = meta.variants.map(
      (v) => `\`${v.attribute}\` (${v.values.map((x) => x.value).join(', ')})`,
    );
    const states = [...new Set(meta.states.flatMap((s) => s.selectors))].map((s) => `\`${s}\``);
    sections.push('', `- ${meta.name}: ${[...variants, ...states].join(', ') || 'none'}`);
  }
  return `${sections.join('\n')}\n`;
}

describe('the public API (0153)', () => {
  test('matches API.md: a change here is a change users can see', async () => {
    await expect(report()).toMatchFileSnapshot('../API.md');
  });

  test('every component root belongs to a component the metadata documents', () => {
    // A root in a file no metadata describes would be public by accident.
    const documented = new Set(
      components.flatMap((meta) =>
        meta.anatomy.flatMap((part) =>
          part.kind === 'import' ? [extracted[part.name]?.file ?? ''] : [],
        ),
      ),
    );
    const undocumented = [...rootClasses().entries()]
      .filter(([file, classes]) => classes.length > 0 && !documented.has(file))
      .map(([file]) => file);
    expect(undocumented).toEqual([]);
  });
});
