/**
 * Generated by `pnpm --filter @rockaway/react metadata` from the `*.meta.ts`
 * files in src/components (scripts/extract.ts). Do not edit: add a component's
 * `.meta.ts` and regenerate. On a merge conflict, take either side and
 * regenerate. A test fails when this is stale.
 */
import { badgeMeta } from '../components/badge.meta.ts';
import { buttonMeta } from '../components/button.meta.ts';
import { calloutMeta } from '../components/callout.meta.ts';
import { checkboxMeta } from '../components/checkbox.meta.ts';
import { codeBlockMeta } from '../components/code-block.meta.ts';
import { dialogMeta } from '../components/dialog.meta.ts';
import { dividerMeta } from '../components/divider.meta.ts';
import { formMeta } from '../components/field.meta.ts';
import { fieldsetMeta } from '../components/fieldset.meta.ts';
import { frameMeta } from '../components/frame.meta.ts';
import { keyHintMeta } from '../components/key-hint.meta.ts';
import { keymapMeta } from '../components/keymap.meta.ts';
import { linkMeta } from '../components/link.meta.ts';
import { listMeta } from '../components/list.meta.ts';
import { overlayMeta } from '../components/overlay.meta.ts';
import { panesMeta } from '../components/panes.meta.ts';
import { tableMeta } from '../components/table.meta.ts';
import { textFieldMeta } from '../components/text-field.meta.ts';
import { tooltipMeta } from '../components/tooltip.meta.ts';
import { treeMeta } from '../components/tree.meta.ts';
import type { ComponentMetaInput } from './schema.ts';

/** Every component's metadata, by the file it is written in. */
export const registry: readonly { readonly file: string; readonly meta: ComponentMetaInput }[] = [
  { file: 'badge', meta: badgeMeta },
  { file: 'button', meta: buttonMeta },
  { file: 'callout', meta: calloutMeta },
  { file: 'checkbox', meta: checkboxMeta },
  { file: 'code-block', meta: codeBlockMeta },
  { file: 'dialog', meta: dialogMeta },
  { file: 'divider', meta: dividerMeta },
  { file: 'field', meta: formMeta },
  { file: 'fieldset', meta: fieldsetMeta },
  { file: 'frame', meta: frameMeta },
  { file: 'key-hint', meta: keyHintMeta },
  { file: 'keymap', meta: keymapMeta },
  { file: 'link', meta: linkMeta },
  { file: 'list', meta: listMeta },
  { file: 'overlay', meta: overlayMeta },
  { file: 'panes', meta: panesMeta },
  { file: 'table', meta: tableMeta },
  { file: 'text-field', meta: textFieldMeta },
  { file: 'tooltip', meta: tooltipMeta },
  { file: 'tree', meta: treeMeta },
];
