/**
 * Generated by `pnpm --filter @rockaway/react metadata` from the `*.meta.ts`
 * files in src/components (scripts/extract.ts). Do not edit: add a component's
 * `.meta.ts` and regenerate. On a merge conflict, take either side and
 * regenerate. A test fails when this is stale.
 */
import { badgeMeta } from '../components/badge.meta.ts';
import { breadcrumbsMeta } from '../components/breadcrumbs.meta.ts';
import { buttonMeta } from '../components/button.meta.ts';
import { calloutMeta } from '../components/callout.meta.ts';
import { cardMeta } from '../components/card.meta.ts';
import { checkboxMeta } from '../components/checkbox.meta.ts';
import { codeBlockMeta } from '../components/code-block.meta.ts';
import { comboBoxMeta } from '../components/combobox.meta.ts';
import { dividerMeta } from '../components/divider.meta.ts';
import { formMeta } from '../components/field.meta.ts';
import { fieldsetMeta } from '../components/fieldset.meta.ts';
import { frameMeta } from '../components/frame.meta.ts';
import { keyHintMeta } from '../components/key-hint.meta.ts';
import { keymapMeta } from '../components/keymap.meta.ts';
import { linkTreeMeta } from '../components/link-tree.meta.ts';
import { linkMeta } from '../components/link.meta.ts';
import { listMeta } from '../components/list.meta.ts';
import { menuMeta } from '../components/menu.meta.ts';
import { overlayMeta } from '../components/overlay.meta.ts';
import { panesMeta } from '../components/panes.meta.ts';
import { pictureMeta } from '../components/picture.meta.ts';
import { popoverMeta } from '../components/popover.meta.ts';
import { radioGroupMeta } from '../components/radio-group.meta.ts';
import { selectMeta } from '../components/select.meta.ts';
import { skipLinkMeta } from '../components/skip-link.meta.ts';
import { statusBarMeta } from '../components/status-bar.meta.ts';
import { switchMeta } from '../components/switch.meta.ts';
import { tableMeta } from '../components/table.meta.ts';
import { tabsMeta } from '../components/tabs.meta.ts';
import { textFieldMeta } from '../components/text-field.meta.ts';
import { toolbarMeta } from '../components/toolbar.meta.ts';
import { treeMeta } from '../components/tree.meta.ts';
import type { ComponentMetaInput } from './schema.ts';

/** Every component's metadata, by the file it is written in. */
export const registry: readonly { readonly file: string; readonly meta: ComponentMetaInput }[] = [
  { file: 'badge', meta: badgeMeta },
  { file: 'breadcrumbs', meta: breadcrumbsMeta },
  { file: 'button', meta: buttonMeta },
  { file: 'callout', meta: calloutMeta },
  { file: 'card', meta: cardMeta },
  { file: 'checkbox', meta: checkboxMeta },
  { file: 'code-block', meta: codeBlockMeta },
  { file: 'combobox', meta: comboBoxMeta },
  { file: 'divider', meta: dividerMeta },
  { file: 'field', meta: formMeta },
  { file: 'fieldset', meta: fieldsetMeta },
  { file: 'frame', meta: frameMeta },
  { file: 'key-hint', meta: keyHintMeta },
  { file: 'keymap', meta: keymapMeta },
  { file: 'link-tree', meta: linkTreeMeta },
  { file: 'link', meta: linkMeta },
  { file: 'list', meta: listMeta },
  { file: 'menu', meta: menuMeta },
  { file: 'overlay', meta: overlayMeta },
  { file: 'panes', meta: panesMeta },
  { file: 'picture', meta: pictureMeta },
  { file: 'popover', meta: popoverMeta },
  { file: 'radio-group', meta: radioGroupMeta },
  { file: 'select', meta: selectMeta },
  { file: 'skip-link', meta: skipLinkMeta },
  { file: 'status-bar', meta: statusBarMeta },
  { file: 'switch', meta: switchMeta },
  { file: 'table', meta: tableMeta },
  { file: 'tabs', meta: tabsMeta },
  { file: 'text-field', meta: textFieldMeta },
  { file: 'toolbar', meta: toolbarMeta },
  { file: 'tree', meta: treeMeta },
];
