/**
 * Generated by `pnpm --filter @rockaway/react metadata` from the components'
 * TypeScript source and the stylesheets they use (scripts/extract.ts). Do not
 * edit: change the source, then regenerate. A test fails when this is stale.
 */
import type { ExtractedPart } from './schema.ts';

export const extracted: { readonly [component: string]: ExtractedPart } = {
  "Badge": {
    "file": "badge.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "tone",
        "type": "BadgeTone",
        "required": false,
        "description": "What the badge is saying. The colour and the mark only repeat it."
      },
      {
        "name": "mark",
        "type": "boolean",
        "required": false,
        "description": "Draw the tone's mark before the words. `false` draws the delimiters instead, and then the words alone must say the tone.",
        "default": "true"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "VariantProps<typeof badgeVariants>"
    ],
    "tokens": [
      "--rk-bg-accent-subtle",
      "--rk-bg-danger-subtle",
      "--rk-bg-subtle",
      "--rk-bg-success-subtle",
      "--rk-bg-warning-subtle",
      "--rk-border-accent",
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-border-success",
      "--rk-border-warning",
      "--rk-fg-accent",
      "--rk-fg-danger",
      "--rk-fg-muted",
      "--rk-fg-success",
      "--rk-fg-warning"
    ]
  },
  "Button": {
    "file": "button.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "variant",
        "type": "ButtonVariant",
        "required": false,
        "description": "`fill` is the primary: reverse video, which survives forced colors and greyscale because it is not a hue. `danger` is the destructive one, and carries a mark as well as a colour."
      },
      {
        "name": "size",
        "type": "ButtonSize",
        "required": false,
        "description": "`md` is one row; `lg` is three, with a border drawn around the label."
      },
      {
        "name": "delimiters",
        "type": "readonly [string, string] | 'none'",
        "required": false,
        "description": "The delimiters around the label: the theme's control delimiters unless given. Chrome, so they are hidden from the accessible name. `none` for a bare label in a toolbar."
      },
      {
        "name": "keys",
        "type": "string",
        "required": false,
        "description": "The chord that fires it: `mod+s`. It draws the hint beside the label and announces the shortcut, which is how a TUI teaches itself (cairn 0099)."
      },
      {
        "name": "platform",
        "type": "'apple' | 'other' | 'auto'",
        "required": false,
        "default": "'auto'"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "React.CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "VariantProps<typeof buttonVariants>",
      "Omit<AriaButtonProps, 'children' | 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-danger-solid",
      "--rk-bg-inverse",
      "--rk-bg-page",
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-cell-height",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-on-danger",
      "--rk-fg-on-inverse",
      "--rk-size-control-lg",
      "--rk-size-control-md",
      "--rk-x-1"
    ]
  },
  "Divider": {
    "file": "divider.tsx",
    "props": [
      {
        "name": "orientation",
        "type": "'horizontal' | 'vertical'",
        "required": false,
        "default": "'horizontal'"
      },
      {
        "name": "border",
        "type": "BorderSetName",
        "required": false,
        "description": "The weight comes from the set, the same way a frame's border does: the theme's when not given."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "A label sunk into the rule, `╶─ files ───╴`, which is also the separator's accessible name. Drawn on horizontal rules only; a vertical one is still named by it. Too long for the rule, it truncates with the ellipsis."
      },
      {
        "name": "labelAlign",
        "type": "'start' | 'center' | 'end'",
        "required": false,
        "description": "Where the label sits along the rule: near the start, by default."
      },
      {
        "name": "ends",
        "type": "'open' | 'joined'",
        "required": false,
        "description": "`joined` adds the crossing edges at each end, so the table resolves a tee even when there is no border there. Inside a frame it changes nothing — the sides already carry those edges."
      }
    ],
    "inherits": [
      "Omit<ScreenProps, 'draw' | 'contentInset' | 'role' | 'children'>"
    ],
    "tokens": [
      "--rk-border-default",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-font-family-mono"
    ]
  },
  "Frame": {
    "file": "frame.tsx",
    "props": [
      {
        "name": "title",
        "type": "string",
        "required": false,
        "description": "Set into the top edge, truncated by the engine so it never runs past it."
      },
      {
        "name": "titleAlign",
        "type": "'start' | 'center' | 'end'",
        "required": false,
        "description": "Where the title sits in the top edge: after the corner, by default."
      },
      {
        "name": "border",
        "type": "BorderSetName",
        "required": false,
        "description": "Which border set draws the box; the theme's when not given. The junction model resolves the seams."
      },
      {
        "name": "dividers",
        "type": "readonly number[]",
        "required": false,
        "description": "Rows that get a rule across the frame, in cells from the frame's top. They join the sides through the junction model — a divider never draws a corner of its own."
      },
      {
        "name": "dividerBorder",
        "type": "BorderSetName",
        "required": false,
        "description": "Which border set the dividers draw with; the frame's own when not given. A heavy box may hold light dividers (cairn 0073), and the junction table resolves the tee where they meet the sides: `┣━━┫` becomes `┠──┨`."
      },
      {
        "name": "pad",
        "type": "number | Inset",
        "required": false,
        "description": "Padding inside the border, in cells. The border's own cell is added to it, so the default puts content one cell in from the left edge and hard against the rows above and below — the proportions a terminal uses."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "The accessible name, when the title is not the right one to say."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      }
    ],
    "inherits": [
      "Omit<ScreenProps, 'draw' | 'contentInset' | 'title' | 'role' | 'aria-label'>"
    ],
    "tokens": [
      "--rk-border-default",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-font-family-mono"
    ]
  },
  "KeyHint": {
    "file": "key-hint.tsx",
    "props": [
      {
        "name": "keys",
        "type": "string",
        "required": true,
        "description": "`mod+s`, `ctrl+shift+k`, `esc`. `mod` follows the keyboard."
      },
      {
        "name": "platform",
        "type": "'apple' | 'other' | 'auto'",
        "required": false,
        "description": "Which keyboard to render for. Detected after mount by default.",
        "default": "'auto'"
      },
      {
        "name": "notation",
        "type": "'platform' | 'terminal'",
        "required": false,
        "default": "'platform'"
      },
      {
        "name": "decorative",
        "type": "boolean",
        "required": false,
        "description": "Inside a control, where the hint must not join the accessible name: the whole thing goes `aria-hidden`, and the control takes `aria-keyshortcuts`.",
        "default": "false"
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "The action the chord performs: `⌘S save`."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [],
    "tokens": [
      "--rk-fg-accent",
      "--rk-fg-muted",
      "--rk-x-1"
    ]
  },
  "Link": {
    "file": "link.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "newTabLabel",
        "type": "string",
        "required": false,
        "description": "What a reader hears after the label when the link opens a new tab (`target=\"_blank\"`). Said only then, never otherwise.",
        "default": "'(opens in a new tab)'"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaLinkProps, 'children' | 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-bold",
      "--rk-attribute-underline-offset",
      "--rk-attribute-underline-thickness",
      "--rk-bg-page",
      "--rk-cell-width",
      "--rk-fg-accent",
      "--rk-fg-default",
      "--rk-fg-disabled"
    ]
  },
  "List": {
    "file": "list.tsx",
    "props": [
      {
        "name": "rows",
        "type": "number",
        "required": false,
        "description": "How many rows the viewport shows. The list is exactly this tall.",
        "default": "8"
      },
      {
        "name": "total",
        "type": "number",
        "required": false,
        "description": "Rows in the collection, for the scrollbar, when the collection does not hold them all: a list that loads as it scrolls. Counted from the collection otherwise."
      },
      {
        "name": "empty",
        "type": "ReactNode",
        "required": false,
        "description": "What an empty list says, in its first row. `renderEmptyState` replaces it.",
        "default": "'Nothing here.'"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<ListBoxProps<T>, 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted"
    ]
  },
  "ListItem": {
    "file": "list.tsx",
    "props": [
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<ListBoxItemProps<T>, 'className'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted"
    ]
  }
};

/** The tokens the focus ring reads, for a component with the `focus-unframed` state. */
export const focusRingTokens: readonly string[] = [
  "--rk-border-focus",
  "--rk-focus-offset",
  "--rk-focus-width"
];
