/**
 * Generated by `pnpm --filter @rockaway/react metadata` from the components'
 * TypeScript source and the stylesheets they use (scripts/extract.ts). Do not
 * edit: change the source, then regenerate. A test fails when this is stale.
 */
import type { ExtractedPart } from './schema.ts';

export const extracted: { readonly [component: string]: ExtractedPart } = {
  "Button": {
    "file": "button.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "variant",
        "type": "ButtonVariant",
        "required": false,
        "description": "`fill` is the primary: reverse video, which survives forced colors and greyscale because it is not a hue. `danger` is the destructive one, and carries a mark as well as a colour."
      },
      {
        "name": "size",
        "type": "ButtonSize",
        "required": false,
        "description": "`md` is one row; `lg` is three, with a border drawn around the label."
      },
      {
        "name": "delimiters",
        "type": "readonly [string, string] | 'none'",
        "required": false,
        "description": "The delimiters around the label: the theme's control delimiters unless given. Chrome, so they are hidden from the accessible name. `none` for a bare label in a toolbar."
      },
      {
        "name": "keys",
        "type": "string",
        "required": false,
        "description": "The chord that fires it: `mod+s`. It draws the hint beside the label and announces the shortcut, which is how a TUI teaches itself (cairn 0099)."
      },
      {
        "name": "platform",
        "type": "'apple' | 'other' | 'auto'",
        "required": false,
        "default": "'auto'"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "React.CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "VariantProps<typeof buttonVariants>",
      "Omit<AriaButtonProps, 'children' | 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-danger-solid",
      "--rk-bg-inverse",
      "--rk-bg-page",
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-cell-height",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-on-danger",
      "--rk-fg-on-inverse",
      "--rk-size-control-lg",
      "--rk-size-control-md",
      "--rk-x-1"
    ]
  },
  "Description": {
    "file": "field.tsx",
    "props": [
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<TextProps, 'slot' | 'className'>"
    ],
    "tokens": [
      "--rk-attribute-bold",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-x-2",
      "--rk-y-1"
    ]
  },
  "Divider": {
    "file": "divider.tsx",
    "props": [
      {
        "name": "orientation",
        "type": "'horizontal' | 'vertical'",
        "required": false,
        "default": "'horizontal'"
      },
      {
        "name": "border",
        "type": "BorderSetName",
        "required": false,
        "description": "The weight comes from the set, the same way a frame's border does: the theme's when not given."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "A label sunk into the rule: `── files ───`. Horizontal rules only."
      },
      {
        "name": "labelAlign",
        "type": "'start' | 'center' | 'end'",
        "required": false
      },
      {
        "name": "ends",
        "type": "'open' | 'joined'",
        "required": false,
        "description": "`joined` adds the crossing edges at each end, so the table resolves a tee even when there is no border there. Inside a frame it changes nothing — the sides already carry those edges."
      }
    ],
    "inherits": [
      "Omit<ScreenProps, 'draw' | 'contentInset' | 'role' | 'children'>"
    ],
    "tokens": [
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-font-family-mono"
    ]
  },
  "FieldError": {
    "file": "field.tsx",
    "props": [
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaFieldErrorProps, 'className'>"
    ],
    "tokens": [
      "--rk-attribute-bold",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-x-2",
      "--rk-y-1"
    ]
  },
  "FieldFrame": {
    "file": "fieldset.tsx",
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": true,
        "description": "Set into the top edge, and the label a reader hears."
      },
      {
        "name": "isRequired",
        "type": "boolean",
        "required": false
      },
      {
        "name": "isInvalid",
        "type": "boolean",
        "required": false
      },
      {
        "name": "isDisabled",
        "type": "boolean",
        "required": false
      },
      {
        "name": "kind",
        "type": "FieldFrameKind",
        "required": false,
        "description": "`control` is a control's own frame (an `lg` text field): focus inside it makes it heavy (0118's focus-framed). `group` frames several controls, each of which shows its own focus, so focus leaves the frame alone."
      },
      {
        "name": "pad",
        "type": "number | Inset",
        "required": false,
        "description": "Padding inside the border, in cells, as `Frame` takes it."
      },
      {
        "name": "painter",
        "type": "PainterName",
        "required": false
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      }
    ],
    "inherits": [
      "VariantProps<typeof fieldFrameVariants>"
    ],
    "tokens": [
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-border-default",
      "--rk-border-focus",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-font-family-mono"
    ]
  },
  "Fieldset": {
    "file": "fieldset.tsx",
    "props": [
      {
        "name": "legend",
        "type": "string",
        "required": true,
        "description": "Set into the top edge, and the group's accessible name."
      },
      {
        "name": "isRequired",
        "type": "boolean",
        "required": false,
        "description": "Draws the required mark after the legend. Pass the group's own `isRequired`, which its render props carry, as a field passes its own to `Label`: the group's state cannot say, because a checkbox group stops being required once something in it is checked."
      },
      {
        "name": "isInvalid",
        "type": "boolean",
        "required": false,
        "description": "Inside a checkbox or radio group, the group's own when not given."
      },
      {
        "name": "isDisabled",
        "type": "boolean",
        "required": false,
        "description": "Dims the frame. It does not disable what is inside: inside a checkbox or radio group, the group's `isDisabled` does both, and is the frame's when this is not given."
      },
      {
        "name": "pad",
        "type": "number | Inset",
        "required": false
      },
      {
        "name": "painter",
        "type": "PainterName",
        "required": false
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      }
    ],
    "inherits": [],
    "tokens": [
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-border-default",
      "--rk-border-focus",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-font-family-mono"
    ]
  },
  "Form": {
    "file": "field.tsx",
    "props": [
      {
        "name": "labelWidth",
        "type": "number",
        "required": false,
        "description": "The label column, in cells, the gap after the labels included. As wide as the longest label in the form when not given; a label longer than the column wraps inside it."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaFormProps, 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-bold",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-x-2",
      "--rk-y-1"
    ]
  },
  "Frame": {
    "file": "frame.tsx",
    "props": [
      {
        "name": "title",
        "type": "string",
        "required": false,
        "description": "Set into the top edge, truncated by the engine so it never runs past it."
      },
      {
        "name": "titleAlign",
        "type": "'start' | 'center' | 'end'",
        "required": false
      },
      {
        "name": "border",
        "type": "BorderSetName",
        "required": false,
        "description": "Which border set draws the box; the theme's when not given. The junction model resolves the seams."
      },
      {
        "name": "dividers",
        "type": "readonly number[]",
        "required": false,
        "description": "Rows that get a rule across the frame, in cells from the frame's top. They join the sides through the junction model — a divider never draws a corner of its own."
      },
      {
        "name": "pad",
        "type": "number | Inset",
        "required": false,
        "description": "Padding inside the border, in cells. The border's own cell is added to it, so the default puts content one cell in from the left edge and hard against the rows above and below — the proportions a terminal uses."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "The accessible name, when the title is not the right one to say."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      }
    ],
    "inherits": [
      "Omit<ScreenProps, 'draw' | 'contentInset' | 'title' | 'role' | 'aria-label'>"
    ],
    "tokens": [
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-font-family-mono"
    ]
  },
  "KeyHint": {
    "file": "key-hint.tsx",
    "props": [
      {
        "name": "keys",
        "type": "string",
        "required": true,
        "description": "`mod+s`, `ctrl+shift+k`, `esc`. `mod` follows the keyboard."
      },
      {
        "name": "platform",
        "type": "'apple' | 'other' | 'auto'",
        "required": false,
        "description": "Which keyboard to render for. Detected after mount by default.",
        "default": "'auto'"
      },
      {
        "name": "notation",
        "type": "'platform' | 'terminal'",
        "required": false,
        "default": "'platform'"
      },
      {
        "name": "decorative",
        "type": "boolean",
        "required": false,
        "description": "Inside a control, where the hint must not join the accessible name: the whole thing goes `aria-hidden`, and the control takes `aria-keyshortcuts`.",
        "default": "false"
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "The action the chord performs: `⌘S save`."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [],
    "tokens": [
      "--rk-fg-accent",
      "--rk-fg-muted",
      "--rk-x-1"
    ]
  },
  "Label": {
    "file": "field.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "isRequired",
        "type": "boolean",
        "required": false,
        "description": "Draws the required mark in the cell after the label. Pass the field's own `isRequired`, which its render props carry. The mark is `aria-hidden`: the control says it is required with `aria-required`.",
        "default": "false"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaLabelProps, 'className' | 'children'>"
    ],
    "tokens": [
      "--rk-attribute-bold",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-x-2",
      "--rk-y-1"
    ]
  },
  "Link": {
    "file": "link.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "newTabLabel",
        "type": "string",
        "required": false,
        "description": "What a reader hears after the label when the link opens a new tab (`target=\"_blank\"`). Said only then, never otherwise.",
        "default": "'(opens in a new tab)'"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaLinkProps, 'children' | 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-bold",
      "--rk-attribute-underline-offset",
      "--rk-attribute-underline-thickness",
      "--rk-bg-page",
      "--rk-cell-width",
      "--rk-fg-accent",
      "--rk-fg-default",
      "--rk-fg-disabled"
    ]
  },
  "List": {
    "file": "list.tsx",
    "props": [
      {
        "name": "rows",
        "type": "number",
        "required": false,
        "description": "How many rows the viewport shows. The list is exactly this tall.",
        "default": "8"
      },
      {
        "name": "total",
        "type": "number",
        "required": false,
        "description": "Rows in the collection, for the scrollbar. Counted from the items if omitted."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<ListBoxProps<T>, 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-inverse",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-fg-on-inverse"
    ]
  },
  "ListItem": {
    "file": "list.tsx",
    "props": [
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<ListBoxItemProps<T>, 'className'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-inverse",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-fg-on-inverse"
    ]
  }
};

/** The tokens the focus ring reads, for a component with the `focus-unframed` state. */
export const focusRingTokens: readonly string[] = [
  "--rk-border-focus",
  "--rk-focus-offset",
  "--rk-focus-width"
];
