/**
 * Generated by `pnpm --filter @rockaway/react metadata` from the components'
 * TypeScript source and the stylesheets they use (scripts/extract.ts). Do not
 * edit: change the source, then regenerate. A test fails when this is stale.
 */
import type { ExtractedPart } from './schema.ts';

export const extracted: { readonly [component: string]: ExtractedPart } = {
  "Badge": {
    "file": "badge.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "tone",
        "type": "BadgeTone",
        "required": false,
        "description": "What the badge is saying. The colour and the mark only repeat it."
      },
      {
        "name": "mark",
        "type": "boolean",
        "required": false,
        "description": "Draw the tone's mark before the words. `false` draws the delimiters instead, and then the words alone must say the tone.",
        "default": "true"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "VariantProps<typeof badgeVariants>"
    ],
    "tokens": [
      "--rk-bg-accent-subtle",
      "--rk-bg-danger-subtle",
      "--rk-bg-subtle",
      "--rk-bg-success-subtle",
      "--rk-bg-warning-subtle",
      "--rk-border-accent",
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-border-success",
      "--rk-border-warning",
      "--rk-fg-accent",
      "--rk-fg-danger",
      "--rk-fg-muted",
      "--rk-fg-success",
      "--rk-fg-warning"
    ],
    "marks": [],
    "level": "strict"
  },
  "Button": {
    "file": "button.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "variant",
        "type": "ButtonVariant",
        "required": false,
        "description": "`fill` is the primary: reverse video, which survives forced colors and greyscale because it is not a hue. `danger` is the destructive one, and carries the theme's `!` in its mark cell as well as its colour."
      },
      {
        "name": "delimiters",
        "type": "readonly [string, string] | 'none'",
        "required": false,
        "description": "The delimiters around the label: the theme's control delimiters unless given. Chrome, so they are hidden from the accessible name. `none` for a bare label in a toolbar, which drops the cell of air either side with them. A `danger` button keeps its delimiters whatever this says, because its mark has to have a cell to sit in."
      },
      {
        "name": "keys",
        "type": "string",
        "required": false,
        "description": "The chord that fires it: `mod+s`. It draws the hint beside the label and announces the shortcut, which is how a TUI teaches itself (cairn 0099). Inside a `Keymap` it also binds it: the chord presses the button, and the help screen lists it under the button's label (cairn 0225). Outside one, the app listens for the chord itself."
      },
      {
        "name": "platform",
        "type": "Platform | 'auto'",
        "required": false,
        "default": "'auto'"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "React.CSSProperties",
        "required": false
      },
      {
        "name": "ref",
        "type": "Ref<HTMLButtonElement>",
        "required": false,
        "description": "The button element, for an app that focuses it or a Keymap binding that presses it (cairn 0224). An object or a callback; Button keeps its own beside it."
      }
    ],
    "inherits": [
      "VariantProps<typeof buttonVariants>",
      "Omit<AriaButtonProps, 'children' | 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-danger-solid",
      "--rk-bg-inverse",
      "--rk-bg-page",
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-cell-height",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-on-danger",
      "--rk-fg-on-inverse",
      "--rk-size-control-md"
    ],
    "marks": [
      "control"
    ],
    "level": "strict"
  },
  "Callout": {
    "file": "callout.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "tone",
        "type": "CalloutTone",
        "required": false,
        "description": "Which kind of aside it is. The border, the mark and the colour all follow it."
      },
      {
        "name": "title",
        "type": "string",
        "required": false,
        "description": "The words in the top edge, and what a reader hears it called. The tone's name by default."
      },
      {
        "name": "painter",
        "type": "PainterName",
        "required": false,
        "description": "How the frame's lines are stroked. The same cells either way."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "VariantProps<typeof calloutVariants>"
    ],
    "tokens": [
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-font-family-mono",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "strict"
  },
  "Cell": {
    "file": "table.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "The value. Text and numbers are cut and aligned in cells; anything else is clipped at the rule."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaCellProps, 'children' | 'className' | 'textValue'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-inverse",
      "--rk-bg-page",
      "--rk-bg-subtle",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-fg-on-inverse",
      "--rk-font-family-mono",
      "--rk-glyph-mark-overflow-end",
      "--rk-glyph-mark-overflow-start",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "strict"
  },
  "Checkbox": {
    "file": "checkbox.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "The words after the box: the checkbox's name."
      },
      {
        "name": "description",
        "type": "ReactNode",
        "required": false,
        "description": "Help, dim, under the row."
      },
      {
        "name": "errorMessage",
        "type": "ReactNode | ((validation: ValidationResult) => ReactNode)",
        "required": false,
        "description": "Words for the error; the field's own validation messages when not given."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "Omit<CheckboxFieldProps, 'children' | 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-page",
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-accent",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled"
    ],
    "marks": [
      "control"
    ],
    "level": "strict"
  },
  "CheckboxGroup": {
    "file": "checkbox.tsx",
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": true,
        "description": "Set into the frame's top edge, and the group's name."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "The checkboxes, one row each."
      },
      {
        "name": "description",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "errorMessage",
        "type": "ReactNode | ((validation: ValidationResult) => ReactNode)",
        "required": false
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaCheckboxGroupProps, 'children' | 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-page",
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-accent",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled"
    ],
    "marks": [
      "control"
    ],
    "level": "standard"
  },
  "CodeBlock": {
    "file": "code-block.tsx",
    "props": [
      {
        "name": "code",
        "type": "string",
        "required": true,
        "description": "The code, exactly: what is shown, what is copied."
      },
      {
        "name": "tokens",
        "type": "readonly CodeLine[]",
        "required": false,
        "description": "The same code, highlighted: one line of tokens per line, each token a role from the syntax tokens (0144). Joined, it must be `code`."
      },
      {
        "name": "lang",
        "type": "string",
        "required": false,
        "description": "The language, for a reader, and the title when there is none."
      },
      {
        "name": "copyable",
        "type": "boolean",
        "required": false,
        "description": "A copy button in the top edge. On by default; a block with no frame has none.",
        "default": "true"
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "The block's accessible name, when the title is not the right one."
      }
    ],
    "inherits": [
      "Omit<ScreenProps, 'draw' | 'contentInset' | 'children' | 'role' | 'rows' | 'title'>",
      "Omit<CodeBlockOptions, 'copyable'>"
    ],
    "tokens": [
      "--rk-bg-page",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-muted",
      "--rk-font-family-mono",
      "--rk-glyph-mark-overflow-end",
      "--rk-glyph-mark-overflow-start",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "standard"
  },
  "CodeSnapshot": {
    "file": "code-block.tsx",
    "props": [
      {
        "name": "text",
        "type": "string",
        "required": true,
        "description": "The text snapshot, as `toText` writes it."
      },
      {
        "name": "label",
        "type": "string",
        "required": true,
        "description": "What the snapshot shows, said in words: a reader hears this, not the box characters one by one."
      },
      {
        "name": "title",
        "type": "string",
        "required": false,
        "description": "Set into the top edge: what it is a snapshot of."
      },
      {
        "name": "copyable",
        "type": "boolean",
        "required": false,
        "description": "A copy button in the top edge. On by default.",
        "default": "true"
      }
    ],
    "inherits": [
      "Omit<ScreenProps, 'draw' | 'contentInset' | 'children' | 'role' | 'rows' | 'title'>"
    ],
    "tokens": [
      "--rk-bg-page",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-muted",
      "--rk-font-family-mono",
      "--rk-glyph-mark-overflow-end",
      "--rk-glyph-mark-overflow-start",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "standard"
  },
  "Column": {
    "file": "table.tsx",
    "props": [
      {
        "name": "children",
        "type": "string",
        "required": true,
        "description": "The header's words."
      },
      {
        "name": "width",
        "type": "ColumnWidth",
        "required": false,
        "description": "Content cells (`12`), a share of the room left (`'1fr'`), or its widest value (`'auto'`).",
        "default": "'auto'"
      },
      {
        "name": "minWidth",
        "type": "number",
        "required": false,
        "description": "The fewest content cells a share column shrinks to."
      },
      {
        "name": "align",
        "type": "'start' | 'end'",
        "required": false,
        "description": "`end` for numbers: they right-align on a cell boundary.",
        "default": "'start'"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaColumnProps, 'children' | 'className' | 'width' | 'minWidth' | 'textValue'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-inverse",
      "--rk-bg-page",
      "--rk-bg-subtle",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-fg-on-inverse",
      "--rk-font-family-mono",
      "--rk-glyph-mark-overflow-end",
      "--rk-glyph-mark-overflow-start",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "strict"
  },
  "Description": {
    "file": "field.tsx",
    "props": [
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<TextProps, 'slot' | 'className'>"
    ],
    "tokens": [
      "--rk-attribute-bold",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-x-2",
      "--rk-y-1"
    ],
    "marks": [],
    "level": "standard"
  },
  "Divider": {
    "file": "divider.tsx",
    "props": [
      {
        "name": "orientation",
        "type": "'horizontal' | 'vertical'",
        "required": false,
        "default": "'horizontal'"
      },
      {
        "name": "border",
        "type": "BorderSetName",
        "required": false,
        "description": "The weight comes from the set, the same way a frame's border does: the theme's when not given."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "A label sunk into the rule, `╶─ files ───╴`, which is also the separator's accessible name. Drawn on horizontal rules only; a vertical one is still named by it. Too long for the rule, it truncates with the ellipsis."
      },
      {
        "name": "labelAlign",
        "type": "'start' | 'center' | 'end'",
        "required": false,
        "description": "Where the label sits along the rule: near the start, by default."
      },
      {
        "name": "ends",
        "type": "'open' | 'joined'",
        "required": false,
        "description": "`joined` adds the crossing edges at each end, so the table resolves a tee even when there is no border there. Inside a frame it changes nothing — the sides already carry those edges."
      }
    ],
    "inherits": [
      "Omit<ScreenProps, 'draw' | 'contentInset' | 'role' | 'children'>"
    ],
    "tokens": [
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-font-family-mono",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [],
    "level": "standard"
  },
  "FieldError": {
    "file": "field.tsx",
    "props": [
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaFieldErrorProps, 'className'>"
    ],
    "tokens": [
      "--rk-attribute-bold",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-x-2",
      "--rk-y-1"
    ],
    "marks": [],
    "level": "standard"
  },
  "FieldFrame": {
    "file": "fieldset.tsx",
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": true,
        "description": "Set into the top edge, and the label a reader hears."
      },
      {
        "name": "isRequired",
        "type": "boolean",
        "required": false
      },
      {
        "name": "isInvalid",
        "type": "boolean",
        "required": false
      },
      {
        "name": "isDisabled",
        "type": "boolean",
        "required": false
      },
      {
        "name": "kind",
        "type": "FieldFrameKind",
        "required": false,
        "description": "`control` is a control's own frame (an `lg` text field): focus inside it makes it heavy (0118's focus-framed). `group` frames several controls, each of which shows its own focus, so focus leaves the frame alone."
      },
      {
        "name": "pad",
        "type": "number | Inset",
        "required": false,
        "description": "Padding inside the border, in cells, as `Frame` takes it."
      },
      {
        "name": "painter",
        "type": "PainterName",
        "required": false
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      }
    ],
    "inherits": [
      "VariantProps<typeof fieldFrameVariants>"
    ],
    "tokens": [
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-border-default",
      "--rk-border-focus",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-font-family-mono",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "standard"
  },
  "Fieldset": {
    "file": "fieldset.tsx",
    "props": [
      {
        "name": "legend",
        "type": "string",
        "required": true,
        "description": "Set into the top edge, and the group's accessible name."
      },
      {
        "name": "isRequired",
        "type": "boolean",
        "required": false,
        "description": "Draws the required mark after the legend. Pass the group's own `isRequired`, which its render props carry, as a field passes its own to `Label`: the group's state cannot say, because a checkbox group stops being required once something in it is checked."
      },
      {
        "name": "isInvalid",
        "type": "boolean",
        "required": false,
        "description": "Inside a checkbox or radio group, the group's own when not given."
      },
      {
        "name": "isDisabled",
        "type": "boolean",
        "required": false,
        "description": "Dims the frame. It does not disable what is inside: inside a checkbox or radio group, the group's `isDisabled` does both, and is the frame's when this is not given."
      },
      {
        "name": "pad",
        "type": "number | Inset",
        "required": false
      },
      {
        "name": "painter",
        "type": "PainterName",
        "required": false
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      }
    ],
    "inherits": [],
    "tokens": [
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-border-default",
      "--rk-border-focus",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-font-family-mono",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "standard"
  },
  "Form": {
    "file": "field.tsx",
    "props": [
      {
        "name": "labelWidth",
        "type": "number",
        "required": false,
        "description": "The label column, in cells, the gap after the labels included. As wide as the longest label in the form when not given; a label longer than the column wraps inside it."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaFormProps, 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-bold",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-x-2",
      "--rk-y-1"
    ],
    "marks": [],
    "level": "strict"
  },
  "Frame": {
    "file": "frame.tsx",
    "props": [
      {
        "name": "title",
        "type": "string",
        "required": false,
        "description": "Set into the top edge, truncated by the engine so it never runs past it."
      },
      {
        "name": "titleAlign",
        "type": "'start' | 'center' | 'end'",
        "required": false,
        "description": "Where the title sits in the top edge: after the corner, by default."
      },
      {
        "name": "border",
        "type": "BorderSetName",
        "required": false,
        "description": "Which border set draws the box; the theme's when not given. The junction model resolves the seams."
      },
      {
        "name": "dividers",
        "type": "readonly number[]",
        "required": false,
        "description": "Rows that get a rule across the frame, in cells from the frame's top. They join the sides through the junction model — a divider never draws a corner of its own."
      },
      {
        "name": "dividerBorder",
        "type": "BorderSetName",
        "required": false,
        "description": "Which border set the dividers draw with; the frame's own when not given. A heavy box may hold light dividers (cairn 0073), and the junction table resolves the tee where they meet the sides: `┣━━┫` becomes `┠──┨`."
      },
      {
        "name": "pad",
        "type": "number | Inset",
        "required": false,
        "description": "Padding inside the border, in cells. The border's own cell is added to it, so the default puts content one cell in from the left edge and hard against the rows above and below — the proportions a terminal uses."
      },
      {
        "name": "surface",
        "type": "Surface",
        "required": false,
        "description": "The ground the frame sits on, border cells included: `sunken`, `base` (the default), `raised` or `overlay`. Unset, the frame is transparent and shows what is behind it."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "The accessible name, when the title is not the right one to say."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      }
    ],
    "inherits": [
      "Omit<ScreenProps, 'draw' | 'contentInset' | 'title' | 'role' | 'aria-label'>"
    ],
    "tokens": [
      "--rk-bg-subtle",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-font-family-mono",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "strict"
  },
  "KeyHint": {
    "file": "key-hint.tsx",
    "props": [
      {
        "name": "keys",
        "type": "string",
        "required": true,
        "description": "`mod+s`, `ctrl+shift+k`, `esc`. `mod` follows the keyboard."
      },
      {
        "name": "platform",
        "type": "Platform | 'auto'",
        "required": false,
        "description": "Which keyboard to render for. The reader's by default, through `usePlatform()`.",
        "default": "'auto'"
      },
      {
        "name": "notation",
        "type": "KeyNotation",
        "required": false,
        "default": "'platform'"
      },
      {
        "name": "decorative",
        "type": "boolean",
        "required": false,
        "description": "Inside a control, where the hint must not join the accessible name: the whole thing goes `aria-hidden`, and the control takes `aria-keyshortcuts`.",
        "default": "false"
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "The action the chord performs: `⌘S save`."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [],
    "tokens": [
      "--rk-fg-accent",
      "--rk-fg-muted",
      "--rk-x-1"
    ],
    "marks": [],
    "level": "standard"
  },
  "Keymap": {
    "file": "keymap.tsx",
    "props": [
      {
        "name": "modal",
        "type": "boolean",
        "required": false,
        "description": "A scope that hides every binding outside it while it is mounted: a dialog's, so the page behind it does not answer the keys.",
        "default": "false"
      },
      {
        "name": "timeout",
        "type": "number",
        "required": false,
        "description": "At the root: how long the second key of a sequence may take, in milliseconds."
      },
      {
        "name": "onConflict",
        "type": "(conflict: KeymapConflict) => void",
        "required": false,
        "description": "At the root: told of each conflict once. A console warning unless given."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      }
    ],
    "inherits": [],
    "tokens": [
      "--rk-fg-default",
      "--rk-x-2"
    ],
    "marks": [],
    "level": "standard"
  },
  "KeymapHelp": {
    "file": "keymap.tsx",
    "props": [
      {
        "name": "platform",
        "type": "Platform | 'auto'",
        "required": false,
        "description": "Which keyboard to draw the chords for. The reader's by default.",
        "default": "'auto'"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [],
    "tokens": [
      "--rk-fg-default",
      "--rk-x-2"
    ],
    "marks": [],
    "level": "standard"
  },
  "Label": {
    "file": "field.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "isRequired",
        "type": "boolean",
        "required": false,
        "description": "Draws the required mark in the cell after the label. Pass the field's own `isRequired`, which its render props carry. The mark is `aria-hidden`: the control says it is required with `aria-required`.",
        "default": "false"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaLabelProps, 'className' | 'children'>"
    ],
    "tokens": [
      "--rk-attribute-bold",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-danger",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-x-2",
      "--rk-y-1"
    ],
    "marks": [],
    "level": "standard"
  },
  "Link": {
    "file": "link.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "newTabLabel",
        "type": "string",
        "required": false,
        "description": "What a reader hears after the label when the link opens a new tab (`target=\"_blank\"`). Said only then, never otherwise.",
        "default": "'(opens in a new tab)'"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaLinkProps, 'children' | 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-bold",
      "--rk-attribute-underline-offset",
      "--rk-attribute-underline-thickness",
      "--rk-bg-page",
      "--rk-cell-width",
      "--rk-fg-accent",
      "--rk-fg-default",
      "--rk-fg-disabled"
    ],
    "marks": [
      "control"
    ],
    "level": "standard"
  },
  "LinkComponentProvider": {
    "file": "link.tsx",
    "props": [
      {
        "name": "component",
        "type": "LinkComponent",
        "required": true,
        "description": "The framework's link, which every link the system draws renders through."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      }
    ],
    "inherits": [],
    "tokens": [
      "--rk-attribute-bold",
      "--rk-attribute-underline-offset",
      "--rk-attribute-underline-thickness",
      "--rk-bg-page",
      "--rk-cell-width",
      "--rk-fg-accent",
      "--rk-fg-default",
      "--rk-fg-disabled"
    ],
    "marks": [
      "control"
    ],
    "level": "standard"
  },
  "List": {
    "file": "list.tsx",
    "props": [
      {
        "name": "rows",
        "type": "number",
        "required": false,
        "description": "How many rows the viewport shows. The list is exactly this tall.",
        "default": "8"
      },
      {
        "name": "total",
        "type": "number",
        "required": false,
        "description": "Rows in the collection, for the scrollbar, when the collection does not hold them all: a list that loads as it scrolls. Counted from the collection otherwise."
      },
      {
        "name": "empty",
        "type": "ReactNode",
        "required": false,
        "description": "What an empty list says, in its first row. `renderEmptyState` replaces it.",
        "default": "EMPTY"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<ListBoxProps<T>, 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "strict"
  },
  "ListItem": {
    "file": "list.tsx",
    "props": [
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<ListBoxItemProps<T>, 'className'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "strict"
  },
  "Menu": {
    "file": "menu.tsx",
    "props": [
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaMenuProps<T>, 'className' | 'style'>",
      "Pick<PopoverProps, 'placement' | 'maxRows' | 'shouldFlip' | 'boundaryElement'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-x-2",
      "--rk-x-3"
    ],
    "marks": [],
    "level": "strict"
  },
  "MenuItem": {
    "file": "menu.tsx",
    "props": [
      {
        "name": "keys",
        "type": "string",
        "required": false,
        "description": "A chord, `mod+s`: drawn right-aligned as a KeyHint, announced as `aria-keyshortcuts`."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaMenuItemProps<T>, 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-x-2",
      "--rk-x-3"
    ],
    "marks": [],
    "level": "strict"
  },
  "MenuSection": {
    "file": "menu.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "The items. For items from data, a React Aria `Collection` among them."
      },
      {
        "name": "title",
        "type": "string",
        "required": false,
        "description": "The section's title, set into the rule above it in the frame, and the name its group is announced by."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaMenuSectionProps<T>, 'className' | 'style' | 'children'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-x-2",
      "--rk-x-3"
    ],
    "marks": [],
    "level": "strict"
  },
  "MenuSeparator": {
    "file": "menu.tsx",
    "props": [
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-x-2",
      "--rk-x-3"
    ],
    "marks": [],
    "level": "strict"
  },
  "OverlayLayer": {
    "file": "overlay.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      }
    ],
    "inherits": [],
    "tokens": [
      "--rk-bg-page",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-font-family-mono",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ]
  },
  "OverlayModal": {
    "file": "overlay.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "minCols",
        "type": "number",
        "required": false,
        "description": "The fewest columns the surface may be, its frame's two included."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<ModalOverlayProps, 'children' | 'className' | 'style' | 'UNSTABLE_portalContainer'>",
      "Omit<OverlaySurfaceOptions, 'minCols'>"
    ],
    "tokens": [
      "--rk-bg-page",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-font-family-mono",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "standard"
  },
  "OverlayPopover": {
    "file": "overlay.tsx",
    "props": [
      {
        "name": "maxRows",
        "type": "number",
        "required": false,
        "description": "The most rows the surface may take before its content scrolls."
      },
      {
        "name": "minCols",
        "type": "number | 'trigger'",
        "required": false,
        "description": "The fewest columns the surface may be, its frame's two included: a number, or `'trigger'` for as wide as its trigger, in whole cells (a select's list). A sheet is as wide as the viewport whatever this says."
      },
      {
        "name": "padding",
        "type": "OverlayPadding",
        "required": false,
        "description": "Cells between the frame and the content, `{ x: 1, y: 0 }` by default. A menu takes `{ x: 0, y: 0 }`, so a highlighted row runs from side to side."
      },
      {
        "name": "dividers",
        "type": "readonly OverlayDivider[]",
        "required": false,
        "description": "Rules across the surface, at rows of the content: `row: 0` is a rule on the content's first row, drawn in the frame and joining its sides. They move with the content as it scrolls, and are not drawn while scrolled out of sight. The content leaves those rows empty: a menu's separator, or the row a section's heading is set into."
      },
      {
        "name": "painter",
        "type": "PainterName",
        "required": false,
        "description": "The painter, `glyph` or `rule`. By default, the painter of the screen the overlay was opened from, so a popover from a ruled frame is ruled too."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "shift",
        "type": "OverlayShift",
        "required": false,
        "description": "An offset in whole cells, `{ main: 0, cross: 0 }` by default. A submenu takes `{ main: 1, cross: -1 }`: beside its parent's frame, its first item level with the item that opened it. Not applied to a sheet."
      }
    ],
    "inherits": [
      "Omit< PopoverProps, 'children' | 'className' | 'style' | 'offset' | 'crossOffset' | 'UNSTABLE_portalContainer' >"
    ],
    "tokens": [
      "--rk-bg-page",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-font-family-mono",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "standard"
  },
  "Pane": {
    "file": "panes.tsx",
    "props": [
      {
        "name": "size",
        "type": "PaneSize",
        "required": false,
        "description": "Cells, a share of what is left (`'2fr'`), or `'auto'`. `'auto'` by default."
      },
      {
        "name": "min",
        "type": "number",
        "required": false,
        "description": "The fewest cells of content it takes along the split before it collapses."
      },
      {
        "name": "priority",
        "type": "number",
        "required": false,
        "description": "When there is not room for every pane, the lowest priority collapses first. 0 by default."
      },
      {
        "name": "title",
        "type": "string",
        "required": false,
        "description": "Set into the pane's top edge, and its accessible name."
      },
      {
        "name": "titleAlign",
        "type": "'start' | 'center' | 'end'",
        "required": false,
        "description": "Where the title sits in the top edge: after the corner, by default."
      },
      {
        "name": "pad",
        "type": "number | Inset",
        "required": false,
        "description": "Padding inside the pane's borders, in cells. One across and none down by default, the proportions `Frame` uses."
      },
      {
        "name": "surface",
        "type": "Surface",
        "required": false,
        "description": "The ground under the pane's content and padding: `sunken`, `base` (the default), `raised` or `overlay`. The borders around it stay the screen's."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "The accessible name, when the title is not the right one to say."
      },
      {
        "name": "landmark",
        "type": "boolean",
        "required": false,
        "description": "Whether a named pane is a region landmark. True by default. False makes it a plain container with no name, its title still drawn in its top edge: for a pane whose content is a landmark of its own, a `nav`, `main` or `aside`, which should stay at the top of a reader's list of landmarks."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "The pane's content, or a `Panes` of its own to split it further."
      }
    ],
    "inherits": [],
    "tokens": [
      "--rk-bg-subtle",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-font-family-mono",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "standard"
  },
  "Panes": {
    "file": "panes.tsx",
    "props": [
      {
        "name": "direction",
        "type": "PanesDirection",
        "required": false,
        "description": "`row` puts the panes side by side, `column` stacks them."
      },
      {
        "name": "border",
        "type": "BorderSetName",
        "required": false,
        "description": "Which border set draws every border; the theme's when not given."
      },
      {
        "name": "label",
        "type": "string",
        "required": false,
        "description": "The whole layout's accessible name, which makes it a group."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "`Pane`s, in order."
      }
    ],
    "inherits": [
      "Omit<ScreenProps, 'draw' | 'contentInset' | 'children' | 'role'>"
    ],
    "tokens": [
      "--rk-bg-subtle",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-font-family-mono",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "standard"
  },
  "Picture": {
    "file": "picture.tsx",
    "props": [
      {
        "name": "src",
        "type": "string",
        "required": true
      },
      {
        "name": "alt",
        "type": "string",
        "required": true,
        "description": "What the image shows, for a reader who cannot see it. Empty for a picture that is decoration."
      },
      {
        "name": "ratio",
        "type": "number",
        "required": false,
        "description": "The image's width over its height (`16 / 9`). With `width` and `height` instead, the ratio is theirs. One or the other is needed: it is what sizes the box before the image arrives."
      },
      {
        "name": "width",
        "type": "number",
        "required": false,
        "description": "The image's own width, in pixels, when `ratio` is not given."
      },
      {
        "name": "height",
        "type": "number",
        "required": false,
        "description": "The image's own height, in pixels, when `ratio` is not given."
      },
      {
        "name": "cols",
        "type": "number",
        "required": false,
        "description": "Its width in cells. Every whole cell its container gives it when not given."
      },
      {
        "name": "rows",
        "type": "number",
        "required": false,
        "description": "Its height in rows, cropping the image to it. From the ratio when not given."
      },
      {
        "name": "position",
        "type": "string",
        "required": false,
        "description": "Which part of the image to keep when it is cropped, as `object-position`."
      },
      {
        "name": "caption",
        "type": "ReactNode",
        "required": false,
        "description": "Text on the rows under the image."
      },
      {
        "name": "loading",
        "type": "'lazy' | 'eager'",
        "required": false,
        "description": "Load it when it is near the viewport (the default) or straight away.",
        "default": "'lazy'"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "Pick< ImgHTMLAttributes<HTMLImageElement>, 'srcSet' | 'sizes' | 'crossOrigin' | 'referrerPolicy' | 'fetchPriority' >"
    ],
    "tokens": [
      "--rk-bg-subtle",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-muted"
    ],
    "marks": [],
    "level": "strict"
  },
  "Popover": {
    "file": "popover.tsx",
    "props": [
      {
        "name": "minCols",
        "type": "number | 'trigger'",
        "required": false,
        "description": "The fewest cells across the popover takes, its frame included: `'trigger'` for its trigger's width in whole cells, or a count. `0` lets it be as narrow as what it holds.\n @default 'trigger'",
        "default": "'trigger'"
      }
    ],
    "inherits": [
      "Omit< OverlayPopoverProps, 'crossOffset' | 'containerPadding' | 'maxHeight' | 'arrowBoundaryOffset' | 'arrowSize' >"
    ],
    "tokens": [],
    "marks": [],
    "level": "strict"
  },
  "Row": {
    "file": "table.tsx",
    "props": [
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaRowProps<T>, 'className'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-inverse",
      "--rk-bg-page",
      "--rk-bg-subtle",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-fg-on-inverse",
      "--rk-font-family-mono",
      "--rk-glyph-mark-overflow-end",
      "--rk-glyph-mark-overflow-start",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "strict"
  },
  "Select": {
    "file": "select.tsx",
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": true,
        "description": "The field's name, in the label column."
      },
      {
        "name": "children",
        "type": "ReactNode | ((item: T) => ReactNode)",
        "required": false,
        "description": "The options: `SelectItem`s, or a function of each of `items`."
      },
      {
        "name": "items",
        "type": "Iterable<T>",
        "required": false,
        "description": "The items to render with a function child."
      },
      {
        "name": "cols",
        "type": "number",
        "required": false,
        "description": "The trigger's width in cells, its delimiters included.",
        "default": "24"
      },
      {
        "name": "description",
        "type": "ReactNode",
        "required": false,
        "description": "Help under the trigger, dim, linked to it by `aria-describedby`."
      },
      {
        "name": "errorMessage",
        "type": "FieldErrorProps['children']",
        "required": false,
        "description": "Words for the error under the trigger; the select's own validation's when not given."
      },
      {
        "name": "maxRows",
        "type": "number",
        "required": false,
        "description": "The most rows the popover takes before its rows scroll.",
        "default": "8"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaSelectProps<T>, 'children' | 'className' | 'style' | 'selectionMode'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-page",
      "--rk-bg-surface",
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted"
    ],
    "marks": [
      "control"
    ],
    "level": "strict"
  },
  "SelectItem": {
    "file": "select.tsx",
    "props": [
      {
        "name": "children",
        "type": "string",
        "required": true,
        "description": "The option's words."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<ListBoxItemProps<T>, 'className' | 'children'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-page",
      "--rk-bg-surface",
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted"
    ],
    "marks": [
      "control"
    ],
    "level": "strict"
  },
  "Switch": {
    "file": "switch.tsx",
    "props": [
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "The label: the switch's own words, after the track. It does not change with the state."
      },
      {
        "name": "description",
        "type": "ReactNode",
        "required": false,
        "description": "Help under the switch, dim, linked to it by `aria-describedby`."
      },
      {
        "name": "painter",
        "type": "PainterName",
        "required": false,
        "description": "How the track's line is stroked: weighted like the type, or a hairline.",
        "default": "'glyph'"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "Omit< AriaSwitchFieldProps, | 'children' | 'className' | 'style' | 'isRequired' | 'isInvalid' | 'validate' | 'validationBehavior' >"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-inverse",
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-border-focus",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-on-inverse",
      "--rk-focus-offset",
      "--rk-focus-width",
      "--rk-font-family-mono",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [],
    "level": "strict"
  },
  "Table": {
    "file": "table.tsx",
    "props": [
      {
        "name": "title",
        "type": "string",
        "required": false,
        "description": "Set into the frame's top edge; the table's accessible name unless `aria-label` says otherwise."
      },
      {
        "name": "cols",
        "type": "number",
        "required": false,
        "description": "The room the table has, in cells, its frame included. Measured from its container when not given. A table whose columns do not fit scrolls."
      },
      {
        "name": "border",
        "type": "BorderSetName",
        "required": false
      },
      {
        "name": "painter",
        "type": "PainterName",
        "required": false,
        "default": "'glyph'"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "A TableHeader and a TableBody."
      }
    ],
    "inherits": [
      "Omit<AriaTableProps, 'className' | 'style' | 'children'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-inverse",
      "--rk-bg-page",
      "--rk-bg-subtle",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-fg-on-inverse",
      "--rk-font-family-mono",
      "--rk-glyph-mark-overflow-end",
      "--rk-glyph-mark-overflow-start",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "strict"
  },
  "TableBody": {
    "file": "table.tsx",
    "props": [
      {
        "name": "empty",
        "type": "string",
        "required": false,
        "description": "What an empty table says, in its first row. `renderEmptyState` replaces it.",
        "default": "EMPTY"
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaTableBodyProps<T>, 'className'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-inverse",
      "--rk-bg-page",
      "--rk-bg-subtle",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-fg-on-inverse",
      "--rk-font-family-mono",
      "--rk-glyph-mark-overflow-end",
      "--rk-glyph-mark-overflow-start",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "strict"
  },
  "TableHeader": {
    "file": "table.tsx",
    "props": [
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaTableHeaderProps<T>, 'className'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-inverse",
      "--rk-bg-page",
      "--rk-bg-subtle",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-fg-on-inverse",
      "--rk-font-family-mono",
      "--rk-glyph-mark-overflow-end",
      "--rk-glyph-mark-overflow-start",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "strict"
  },
  "TextField": {
    "file": "text-field.tsx",
    "props": [
      {
        "name": "label",
        "type": "string",
        "required": true,
        "description": "The field's name: inline before a `md` box, in the top edge of a framed one."
      },
      {
        "name": "description",
        "type": "ReactNode",
        "required": false,
        "description": "Help, dim, under the box."
      },
      {
        "name": "errorMessage",
        "type": "ReactNode | ((validation: ValidationResult) => ReactNode)",
        "required": false,
        "description": "Words for the error; the field's own validation messages when not given."
      },
      {
        "name": "placeholder",
        "type": "string",
        "required": false
      },
      {
        "name": "cols",
        "type": "number",
        "required": false,
        "description": "The box's width, in cells: the text it shows at once.",
        "default": "DEFAULT_COLS"
      },
      {
        "name": "size",
        "type": "TextFieldSize",
        "required": false,
        "description": "`md` is one row between the delimiters; `lg` is three, framed, the label in the edge."
      },
      {
        "name": "multiline",
        "type": "boolean",
        "required": false,
        "description": "Several rows, framed, scrolling by whole rows.",
        "default": "false"
      },
      {
        "name": "rows",
        "type": "number",
        "required": false,
        "description": "How many rows a `multiline` box shows.",
        "default": "DEFAULT_ROWS"
      },
      {
        "name": "inputRef",
        "type": "Ref<HTMLInputElement | HTMLTextAreaElement>",
        "required": false,
        "description": "The text box itself, `<input>` or, `multiline`, `<textarea>`: for an app to focus it, select its text or read its caret. An object or a callback; the field keeps its own beside it. `ref` is the field around it."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "VariantProps<typeof textFieldVariants>",
      "Omit<AriaTextFieldProps, 'children' | 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-bg-subtle",
      "--rk-border-control",
      "--rk-border-danger",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "control"
    ],
    "level": "strict"
  },
  "Tree": {
    "file": "tree.tsx",
    "props": [
      {
        "name": "painter",
        "type": "StrokeStyle",
        "required": false,
        "description": "How the guides are stroked: weighted like type, or hairlines. Match the screen it sits in.",
        "default": "'glyph'"
      },
      {
        "name": "disallowTypeAhead",
        "type": "boolean",
        "required": false,
        "description": "No type-ahead: a printable key moves nothing, and reaches the page, for a tree beside single-letter shortcuts (`j`, `k`, `/`). The arrows, Home and End still move. React Aria's own option, which its GridList offers and its Tree honours."
      },
      {
        "name": "onFocusedKeyChange",
        "type": "(key: Key | null) => void",
        "required": false,
        "description": "Called with the row that has focus whenever it changes, and with `null` when focus leaves the tree: what a keymap beside the tree acts on, or what a status bar shows."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      },
      {
        "name": "style",
        "type": "CSSProperties",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaTreeProps<T>, 'className' | 'style'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "strict"
  },
  "TreeItem": {
    "file": "tree.tsx",
    "props": [
      {
        "name": "title",
        "type": "string",
        "required": true,
        "description": "The row's label, and the text type-ahead matches."
      },
      {
        "name": "textValue",
        "type": "string",
        "required": false,
        "description": "What type-ahead matches, when it is not the title."
      },
      {
        "name": "children",
        "type": "ReactNode",
        "required": false,
        "description": "The rows under this one. A row with children carries the expand mark."
      },
      {
        "name": "className",
        "type": "string",
        "required": false
      }
    ],
    "inherits": [
      "Omit<AriaTreeItemProps<T>, 'className' | 'children' | 'textValue'>"
    ],
    "tokens": [
      "--rk-attribute-underline-offset",
      "--rk-bg-surface",
      "--rk-cell-height",
      "--rk-cell-width",
      "--rk-fg-default",
      "--rk-fg-disabled",
      "--rk-fg-muted",
      "--rk-stroke-glyph-gap",
      "--rk-stroke-glyph-heavy",
      "--rk-stroke-glyph-light",
      "--rk-stroke-rule-gap",
      "--rk-stroke-rule-heavy",
      "--rk-stroke-rule-light"
    ],
    "marks": [
      "pane"
    ],
    "level": "strict"
  }
};

/** The tokens the focus ring reads, for a component with the `focus-unframed` state. */
export const focusRingTokens: readonly string[] = [
  "--rk-border-focus",
  "--rk-focus-offset",
  "--rk-focus-width"
];
