/**
 * Terminal themes (cairn 0094).
 *
 * The palette is a terminal palette (0089), so this is the claim made
 * checkable: the same tokens that dress the web write a theme file for
 * Ghostty, Kitty, Alacritty or iTerm2, and reading one back gives the palette
 * it came from.
 *
 * Only the sixteen plus background, foreground, cursor and selection are
 * written. The role slots are ours, a terminal has no idea what they are, and
 * the import derives them again on the way back in.
 */
import { ansiSlots, type Palette } from './ansi.ts';
import { toHex } from './color.ts';
import type { Mode } from './inputs.ts';
import type { ThemeContext } from './themes.ts';

export type TerminalFormat = 'ghostty' | 'kitty' | 'alacritty' | 'iterm2';

export interface ThemeFile {
  readonly format: TerminalFormat;
  /** What the file is usually called for that terminal. */
  readonly filename: string;
  readonly contents: string;
}

const ansiHex = (palette: Palette): string[] => ansiSlots.map((slot) => toHex(palette[slot]));

/** A header as comment lines, for the three formats that comment with `#`. */
const hashed = (header: readonly string[]): string =>
  header.map((line) => (line === '' ? '#' : `# ${line}`).trimEnd()).join('\n');

const withHeader = (header: readonly string[], body: string): string =>
  header.length === 0 ? body : `${hashed(header)}\n${body}`;

function ghostty(palette: Palette, name: string, header: readonly string[]): string {
  const lines = [
    ...(header.length === 0 ? [] : [hashed(header)]),
    `# ${name} — generated by @rockaway/tokens`,
    ...ansiHex(palette).map((hex, i) => `palette = ${i}=${hex}`),
    `background = ${toHex(palette.background)}`,
    `foreground = ${toHex(palette.foreground)}`,
    `cursor-color = ${toHex(palette.cursor)}`,
    `selection-background = ${toHex(palette.selection)}`,
    `selection-foreground = ${toHex(palette.foreground)}`,
  ];
  return `${lines.join('\n')}\n`;
}

function kitty(palette: Palette, name: string, header: readonly string[]): string {
  const lines = [
    ...(header.length === 0 ? [] : [hashed(header)]),
    `# ${name} — generated by @rockaway/tokens`,
    `background ${toHex(palette.background)}`,
    `foreground ${toHex(palette.foreground)}`,
    `cursor ${toHex(palette.cursor)}`,
    `selection_background ${toHex(palette.selection)}`,
    `selection_foreground ${toHex(palette.foreground)}`,
    ...ansiHex(palette).map((hex, i) => `color${i} ${hex}`),
  ];
  return `${lines.join('\n')}\n`;
}

function alacritty(palette: Palette, name: string, header: readonly string[]): string {
  const hex = ansiHex(palette);
  const group = (from: number): string =>
    ['black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white']
      .map((slot, i) => `${slot} = "${hex[from + i]}"`)
      .join('\n');

  return withHeader(
    header,
    `# ${name} — generated by @rockaway/tokens
[colors.primary]
background = "${toHex(palette.background)}"
foreground = "${toHex(palette.foreground)}"

[colors.cursor]
cursor = "${toHex(palette.cursor)}"
text = "${toHex(palette.background)}"

[colors.selection]
background = "${toHex(palette.selection)}"
text = "${toHex(palette.foreground)}"

[colors.normal]
${group(0)}

[colors.bright]
${group(8)}
`,
  );
}

function itermComponents(hex: string): string {
  const channel = (at: number): number => Number.parseInt(hex.slice(at, at + 2), 16) / 255;
  const [red, green, blue] = [channel(1), channel(3), channel(5)];
  return [
    '\t\t<key>Color Space</key>',
    '\t\t<string>sRGB</string>',
    '\t\t<key>Red Component</key>',
    `\t\t<real>${red.toFixed(6)}</real>`,
    '\t\t<key>Green Component</key>',
    `\t\t<real>${green.toFixed(6)}</real>`,
    '\t\t<key>Blue Component</key>',
    `\t\t<real>${blue.toFixed(6)}</real>`,
    '\t\t<key>Alpha Component</key>',
    '\t\t<real>1</real>',
  ].join('\n');
}

/** A plist comment may not hold `--`, so a licence's rules are broken up. */
const xmlComment = (header: readonly string[]): string =>
  header.length === 0
    ? ''
    : `<!--\n${header.map((line) => line.replaceAll('--', '- -')).join('\n')}\n-->\n`;

function iterm2(palette: Palette, header: readonly string[]): string {
  const entry = (key: string, hex: string): string =>
    [`\t<key>${key}</key>`, '\t<dict>', itermComponents(hex), '\t</dict>'].join('\n');

  const entries = [
    ...ansiHex(palette).map((hex, i) => entry(`Ansi ${i} Color`, hex)),
    entry('Background Color', toHex(palette.background)),
    entry('Foreground Color', toHex(palette.foreground)),
    entry('Cursor Color', toHex(palette.cursor)),
    entry('Selection Color', toHex(palette.selection)),
  ];

  return `<?xml version="1.0" encoding="UTF-8"?>
${xmlComment(header)}<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
${entries.join('\n')}
</dict>
</plist>
`;
}

/**
 * Every format, for one palette. `header` goes at the top of each file as
 * comments: for an imported theme, where it came from, what fitting changed,
 * and its licence (0188).
 */
export function terminalThemes(
  palette: Palette,
  name: string,
  header: readonly string[] = [],
): ThemeFile[] {
  return [
    { format: 'ghostty', filename: `${name}`, contents: ghostty(palette, name, header) },
    { format: 'kitty', filename: `${name}.conf`, contents: kitty(palette, name, header) },
    { format: 'alacritty', filename: `${name}.toml`, contents: alacritty(palette, name, header) },
    { format: 'iterm2', filename: `${name}.itermcolors`, contents: iterm2(palette, header) },
  ];
}

/** The slots a terminal theme file holds. */
const written: ReadonlySet<string> = new Set([
  ...ansiSlots,
  'background',
  'foreground',
  'cursor',
  'selection',
]);

/**
 * The header an imported theme's files carry (0188): what it is and where it
 * came from, what fitting to the contrast gate changed — the licences ask that
 * a changed file says so — and the upstream licence in full, which both MIT
 * and Apache-2.0 require to travel with a copy.
 */
export function importedHeader(theme: ThemeContext, mode: Mode, licence: string): string[] {
  const variant = theme.variants?.[mode];
  // Only what a terminal file holds: the role slots fitting may also move are ours.
  const changed = theme.adjustments.filter((a) => a.mode === mode && written.has(a.slot));
  return [
    `${theme.title}${variant ? ` ${variant}` : ''} (${mode}), from ${theme.source}`,
    changed.length === 0
      ? 'Unchanged by @rockaway/tokens: it passes the contrast gate as it is.'
      : 'Changed by @rockaway/tokens, to pass its contrast gate (WCAG 2, in every gamut):',
    ...changed.map((a) => `  ${a.slot}: ${a.from} -> ${a.to}`),
    '',
    `${theme.licence?.spdx} licence. ${theme.licence?.copyright}.`,
    '',
    ...licence
      .trimEnd()
      .split('\n')
      .map((line) => line.trimEnd()),
    '',
  ];
}

/**
 * Read a Ghostty theme back: the format is the simplest of the four, and it is
 * what the round-trip test uses to prove an exported palette imports.
 */
export function parseGhostty(contents: string): {
  colors: string[];
  background: string;
  foreground: string;
} {
  const colors: string[] = [];
  let background = '';
  let foreground = '';
  for (const line of contents.split('\n')) {
    const palette = /^palette\s*=\s*(\d+)\s*=\s*(#[0-9a-f]{6})/i.exec(line);
    if (palette) colors[Number(palette[1])] = palette[2] as string;
    const bg = /^background\s*=\s*(#?[0-9a-f]{6})/i.exec(line);
    if (bg) background = (bg[1] as string).startsWith('#') ? (bg[1] as string) : `#${bg[1]}`;
    const fg = /^foreground\s*=\s*(#?[0-9a-f]{6})/i.exec(line);
    if (fg) foreground = (fg[1] as string).startsWith('#') ? (fg[1] as string) : `#${fg[1]}`;
  }
  return { colors, background, foreground };
}
