/**
 * The public API of @rockaway/tokens, as a report (cairn 0153): the names the
 * entry exports, the paths a package import may reach, the theme names, and
 * every token in the public tiers by name, as the custom property a
 * stylesheet reads. `API.md` is a file snapshot, so a change to any of it is
 * a diff a reviewer sees; a removal or a rename is breaking (0172).
 *
 * A token's *value* is not API: a changed value is a minor. The reference
 * tier (`ansi.*`, `palette.*`, `font.*`) is internal. Components never read
 * it, and its shape has changed twice already (0052, 0065). Read the semantic
 * tier instead.
 */
import path from 'node:path';
import { describe, expect, test } from 'vitest';
import { block, entriesOf, exportsOf } from '../../../scripts/api-surface.ts';
import { vars } from '../src/names.ts';
import { themeNames } from '../src/themes.ts';

const root = path.join(import.meta.dirname, '..');

/** The tiers a user may read. Everything else in `vars` is the reference tier. */
const publicGroups = [
  'bg',
  'fg',
  'border',
  'syntax',
  'attribute',
  'focus',
  'motion',
  'cell',
  'space',
  'row',
  'size',
  'stroke',
  'glyph',
  'conformance',
] as const;

const referenceGroups = ['ansi', 'palette', 'font'];

function report(): string {
  const groupOf = (name: string) => name.split('.')[0] ?? '';
  const names = Object.keys(vars);
  const sections = [
    '# @rockaway/tokens: public API',
    '',
    'Generated by `test/public-api.test.ts` (cairn 0153). A change here is a change to what users rely on: say so in the changeset, and begin it `Breaking:` when something is removed or renamed (0172). A changed token value is not listed here, and is a minor.',
    '',
    '## Entry points',
  ];
  for (const { subpath, files } of entriesOf(root)) {
    const exported = files.flatMap((file) => exportsOf(path.join(root, file)));
    sections.push('', `### \`@rockaway/tokens${subpath === '.' ? '' : subpath.slice(1)}\``);
    if (exported.length > 0) sections.push('', block(exported));
  }
  sections.push('', '## Themes', '', block([...themeNames]));
  sections.push(
    '',
    '## Tokens',
    '',
    'By name, as the custom property a stylesheet reads. The reference tier (`ansi.*`, `palette.*`, `font.*`) is internal and not listed.',
  );
  for (const group of publicGroups) {
    const inGroup = names.filter((name) => groupOf(name) === group).sort();
    sections.push(
      '',
      `### ${group}`,
      '',
      block(inGroup.map((name) => (vars as Record<string, string>)[name]?.slice(4, -1) ?? name)),
    );
  }
  return `${sections.join('\n')}\n`;
}

describe('the public API (0153)', () => {
  test('matches API.md: a change here is a change users can see', async () => {
    await expect(report()).toMatchFileSnapshot('../API.md');
  });

  test('every token is in a public tier or the reference tier: none is unaccounted for', () => {
    const known = new Set<string>([...publicGroups, ...referenceGroups]);
    const unaccounted = Object.keys(vars).filter((name) => !known.has(name.split('.')[0] ?? ''));
    expect(unaccounted).toEqual([]);
  });
});
