/**
 * A Terrazzo plugin that writes `src/names.ts`: every token's CSS custom
 * property, keyed by its DTCG path, for autocompletion and for lint rules that
 * need to know which names exist (cairn 0020).
 */
import { writeFileSync } from 'node:fs';
import type { Plugin } from '@terrazzo/parser';

export function names({ file, input }: { file: string; input: Record<string, string> }): Plugin {
  return {
    name: 'rockaway-names',
    build({ getTransforms }) {
      const entries = getTransforms({ format: 'css', input })
        .map((t) => [t.token.id, t.localID ?? ''] as const)
        .filter(([, v]) => v !== '')
        .sort(([a], [b]) => (a < b ? -1 : 1));
      const lines = entries.map(([id, v]) => `  '${id}': 'var(${v})',`);
      writeFileSync(
        file,
        [
          '// Generated by `pnpm --filter @rockaway/tokens generate`. Do not edit.',
          '',
          '/** Every token as a CSS `var()`, keyed by its DTCG path. */',
          'export const vars = {',
          ...lines,
          '} as const;',
          '',
          'export type TokenName = keyof typeof vars;',
          '',
        ].join('\n'),
      );
    },
  };
}
