/**
 * A Terrazzo plugin that writes `src/names.ts`: every token's CSS custom
 * property, keyed by its DTCG path, for autocompletion and for lint rules that
 * need to know which names exist (cairn 0020).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { Plugin } from '@terrazzo/parser';

export function names({ file, input }: { file: string; input: Record<string, string> }): Plugin {
  return {
    name: 'rockaway-names',
    build({ getTransforms }) {
      const entries = getTransforms({ format: 'css', input })
        .flatMap((t) => {
          const cssVar = t.localID;
          if (!cssVar) return [];
          // A typography token has no shorthand of its own (cairn 0066), so
          // list its parts: `text.body.font-size`, and so on.
          if (t.type === 'MULTI_VALUE' && t.token.$type === 'typography') {
            return Object.keys(t.value as Record<string, unknown>)
              .filter((sub) => sub !== '.')
              .map((sub) => [`${t.token.id}.${sub}`, `${cssVar}-${sub}`] as const);
          }
          return [[t.token.id, cssVar] as const];
        })
        .sort(([a], [b]) => (a < b ? -1 : 1));
      const lines = entries.map(([id, v]) => `  '${id}': 'var(${v})',`);
      mkdirSync(path.dirname(file), { recursive: true });
      writeFileSync(
        file,
        [
          '// Generated by `pnpm --filter @rockaway/tokens generate`. Do not edit.',
          '',
          '/** Every token as a CSS `var()`, keyed by its DTCG path. */',
          'export const vars = {',
          ...lines,
          '} as const;',
          '',
          'export type TokenName = keyof typeof vars;',
          '',
        ].join('\n'),
      );
    },
  };
}
