/**
 * A Terrazzo plugin that writes `css/tailwind.css`: a Tailwind v4 `@theme`
 * block mapping our semantic tokens onto Tailwind's namespaces (cairn 0030).
 *
 * `@theme inline` matters: our values are `var(--rk-…)` references, and inline
 * keeps them as references, so a utility resolves to the same custom property
 * a component reads. Change mode or density and the utilities follow.
 *
 * Tailwind's namespaces already carry the role (`bg-`, `text-`, `border-`), so
 * repeating ours would give `bg-bg-page`. The names below drop the role where
 * Tailwind supplies it and keep it where two roles would collide:
 *
 *   bg.page            → --color-page          bg-page
 *   bg.accent.solid    → --color-accent        bg-accent
 *   fg.default         → --color-ink           text-ink
 *   fg.muted           → --color-muted         text-muted
 *   fg.on-accent       → --color-on-accent     text-on-accent
 *   fg.danger          → --color-danger-ink    text-danger-ink
 *   border.control     → --color-line-control  border-line-control
 *   space.1            → --spacing             p-4 = 4 × the unit
 *   radius.surface     → --radius-surface      rounded-surface
 *   shadow.overlay     → --shadow-overlay      shadow-overlay
 *   text.body          → --text-body           text-body
 *   font.family.sans   → --font-sans           font-sans
 *   motion.easing.enter→ --ease-enter          ease-enter
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { Plugin } from '@terrazzo/parser';

const intents = ['accent', 'info', 'success', 'warning', 'danger'];

/** The Tailwind theme name for a token path, or undefined to leave it out. */
export function themeName(path: string): string | undefined {
  const [group, ...rest] = path.split('.');
  const name = rest.join('-');

  if (group === 'bg') {
    for (const intent of intents) {
      if (name === `${intent}-solid`) return `--color-${intent}`;
      if (name === `${intent}-solid-hover`) return `--color-${intent}-hover`;
      if (name === `${intent}-subtle`) return `--color-${intent}-subtle`;
    }
    return `--color-${name}`;
  }
  if (group === 'fg') {
    if (name === 'default') return '--color-ink';
    if (intents.includes(name)) return `--color-${name}-ink`;
    return `--color-${name}`;
  }
  if (group === 'border') return `--color-line-${name}`;
  if (group === 'radius') return `--radius-${name}`;
  if (group === 'shadow') return `--shadow-${name}`;
  if (group === 'space') return name === '1' ? '--spacing' : undefined;
  if (group === 'font' && rest[0] === 'family') return `--font-${rest[1]}`;
  if (group === 'motion' && rest[0] === 'easing') return `--ease-${rest[1]}`;
  return undefined;
}

export function tailwind({ file, input }: { file: string; input: Record<string, string> }): Plugin {
  return {
    name: 'rockaway-tailwind',
    build({ getTransforms }) {
      const transforms = getTransforms({ format: 'css', input });
      const lines: string[] = [];
      const text: string[] = [];

      for (const t of transforms.sort((a, b) => (a.token.id < b.token.id ? -1 : 1))) {
        const cssVar = t.localID;
        if (!cssVar) continue;
        const id = t.token.id;

        if (t.token.$type === 'typography') {
          const name = id.split('.').slice(1).join('-');
          text.push(`  --text-${name}: var(${cssVar}-font-size);`);
          text.push(`  --text-${name}--line-height: var(${cssVar}-line-height);`);
          text.push(`  --text-${name}--font-weight: var(${cssVar}-font-weight);`);
          continue;
        }

        const name = themeName(id);
        if (name) lines.push(`  ${name}: var(${cssVar});`);
      }

      mkdirSync(path.dirname(file), { recursive: true });
      writeFileSync(
        file,
        [
          '/* Generated by `pnpm --filter @rockaway/tokens generate`. Do not edit. */',
          '',
          '/*',
          ' * Tailwind v4 adapter (cairn 0030). Import it after Tailwind and after',
          ' * the tokens:',
          ' *',
          " *   @import 'tailwindcss';",
          " *   @import '@rockaway/tokens/tokens.css';",
          " *   @import '@rockaway/tokens/tailwind.css';",
          ' *',
          ' * Utilities resolve to the same custom properties the components read,',
          ' * so mode and density carry through without a rebuild.',
          ' */',
          '@theme inline {',
          ...lines,
          '',
          ...text,
          '}',
          '',
        ].join('\n'),
      );
    },
  };
}
