/**
 * The public API of @rockaway/grid, as a report (cairn 0153): every name the
 * entry exports, and the text snapshot format, which users' own snapshots are
 * written in. `API.md` is a file snapshot, so a change to either is a diff a
 * reviewer sees; a removal or a rename is breaking (0172).
 */
import path from 'node:path';
import { describe, expect, test } from 'vitest';
import { block, entriesOf, exportsOf } from '../../../scripts/api-surface.ts';
import { Buffer } from '../src/buffer.ts';
import { drawBox, drawText } from '../src/draw.ts';
import { rect } from '../src/geometry.ts';
import { bufferSerializer } from '../src/snapshot.ts';

const root = path.join(import.meta.dirname, '..');

function report(): string {
  const sections = [
    '# @rockaway/grid: public API',
    '',
    'Generated by `test/public-api.test.ts` (cairn 0153). A change here is a change to what users rely on: say so in the changeset, and begin it `Breaking:` when something is removed or renamed (0172).',
    '',
    '## Entry points',
  ];
  for (const { subpath, files } of entriesOf(root)) {
    const exported = files.flatMap((file) => exportsOf(path.join(root, file)));
    sections.push('', `### \`@rockaway/grid${subpath === '.' ? '' : subpath.slice(1)}\``);
    if (exported.length > 0) sections.push('', block(exported));
  }

  // The snapshot format is public: users' own snapshots are written in it.
  const buffer = Buffer.create({ width: 12, height: 3 }).draw((draft) => {
    drawBox(draft, rect(0, 0, 12, 3), { title: 'format' });
    drawText(draft, { x: 2, y: 1 }, 'a cell');
  });
  const printed = bufferSerializer.serialize(buffer);
  sections.push(
    '',
    '## The text snapshot format',
    '',
    'What `bufferSerializer` prints for a 12 × 3 buffer:',
    '',
    block(printed.split('\n')),
  );
  return `${sections.join('\n')}\n`;
}

describe('the public API (0153)', () => {
  test('matches API.md: a change here is a change users can see', async () => {
    await expect(report()).toMatchFileSnapshot('../API.md');
  });
});
